# Generated by Django 6.0 on 2026-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopeca',
            name='empresa',
            field=models.CharField(choices=[('DIVIDATA', 'Dividata'), ('TORINO', 'Torino')], default='DIVIDATA', max_length=20),
        ),
        migrations.AlterField(
            model_name='grupopeca',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='grupopeca',
            unique_together={('nome', 'empresa')},
        ),
    ]
