# Generated by Django 6.0 on 2026-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0002_grupopeca_empresa_alter_grupopeca_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='codigo_material',
            field=models.IntegerField(default=0),
        ),
    ]
