# Generated by Django 6.0 on 2025-12-19 12:44

import core_rh.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0010_alter_ferias_options_ferias_abono_pecuniario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro'), (13, '13º Salário')])),
                ('ano', models.IntegerField()),
                ('arquivo', models.FileField(upload_to=core_rh.models.contracheque_upload_path)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_ciencia', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('ip_ciencia', models.GenericIPAddressField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracheques', to='core_rh.funcionario')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('funcionario', 'mes', 'ano')},
            },
        ),
    ]
