# Generated by Django 6.0 on 2025-12-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0011_contracheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('dias', models.IntegerField(default=1, verbose_name='Qtd. Dias')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo / CID (Opcional)')),
                ('arquivo', models.FileField(upload_to='atestados/%Y/%m/')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20)),
                ('observacao_rh', models.TextField(blank=True, null=True, verbose_name='Obs. do RH')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='core_rh.funcionario')),
            ],
        ),
    ]
