# Generated by Django 6.0 on 2025-12-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0012_atestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atestado',
            name='dias',
        ),
        migrations.AddField(
            model_name='atestado',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fim'),
        ),
        migrations.AddField(
            model_name='atestado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Início'),
        ),
        migrations.AddField(
            model_name='atestado',
            name='qtd_dias',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Qtd. Dias'),
        ),
        migrations.AddField(
            model_name='atestado',
            name='tipo',
            field=models.CharField(choices=[('DIAS', 'Atestado Médico (Afastamento em Dias)'), ('HORAS', 'Declaração de Comparecimento (Horas)')], default='DIAS', max_length=10),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='data_inicio',
            field=models.DateField(verbose_name='Data do Atestado'),
        ),
    ]
