# Generated by Django 6.0 on 2025-12-29 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0013_remove_atestado_dias_atestado_hora_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Viagem')),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total KM')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Pago', 'Pago')], default='Pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_rh.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Controle de KM',
                'verbose_name_plural': 'Controles de KM',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TrechoKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255, verbose_name='Origem')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distância (KM)')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='core_rh.controlekm')),
            ],
        ),
    ]
