# Generated by Django 6.0 on 2025-12-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0014_controlekm_trechokm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlekm',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='controlekm',
            name='status',
        ),
        migrations.RemoveField(
            model_name='controlekm',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='trechokm',
            name='ordem',
        ),
    ]
