# Generated by Django 6.0 on 2025-12-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0015_remove_controlekm_observacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlekm',
            options={},
        ),
        migrations.AddField(
            model_name='controlekm',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='controlekm',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlekm',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='controlekm',
            name='total_km',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='destino',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='trechokm',
            name='origem',
            field=models.CharField(max_length=255),
        ),
    ]
