# Generated by Django 6.0 on 2025-12-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0016_alter_controlekm_options_controlekm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to='core_rh.funcionario'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='oculta',
            field=models.BooleanField(default=False, help_text='Se marcado, esta equipe não aparecerá na lista principal de seleção.', verbose_name='Equipe Oculta (Apenas Secundária)'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='gestores',
            field=models.ManyToManyField(blank=True, related_name='equipes_gerenciadas', to='core_rh.funcionario'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
