# Generated by Django 6.0 on 2025-12-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0017_equipe_gestor_equipe_oculta_alter_equipe_gestores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlekm',
            name='numero_chamado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Chamado'),
        ),
        migrations.AlterField(
            model_name='controlekm',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Pago', 'Pago'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='DespesaDiversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero_chamado', models.CharField(max_length=50, verbose_name='Nº Chamado')),
                ('tipo', models.CharField(choices=[('Estacionamento', 'Estacionamento'), ('Pedagio', 'Pedágio'), ('Jantar', 'Jantar'), ('Hospedagem', 'Hospedagem'), ('Outra', 'Outra')], max_length=20)),
                ('especificacao', models.CharField(blank=True, help_text="Preencher se for 'Outra'", max_length=255, null=True)),
                ('comprovante', models.FileField(upload_to='despesas_diversas/%Y/%m/')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_rh.funcionario')),
            ],
        ),
    ]
