# Generated by Django 6.0 on 2025-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0018_controlekm_numero_chamado_alter_controlekm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='base',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base de Atendimento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='operacao',
            field=models.CharField(blank=True, help_text='Ex: 013 (Caixa)', max_length=10, null=True, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo Chave PIX'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_veiculo',
            field=models.CharField(blank=True, help_text='Ex: Carro Próprio, Moto, etc.', max_length=50, null=True, verbose_name='Tipo de Veículo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Valor do KM (R$)'),
        ),
    ]
