# Generated by Django 6.0 on 2025-12-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0019_funcionario_agencia_funcionario_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trechokm',
            name='nome_destino',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Destino'),
        ),
        migrations.AddField(
            model_name='trechokm',
            name='nome_origem',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Origem'),
        ),
    ]
