# Generated by Django 6.0 on 2025-12-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0020_trechokm_nome_destino_trechokm_nome_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trechokm',
            name='origem',
            field=models.TextField(verbose_name='Link ou Origem'),
        ),
    ]
