# Generated by Django 6.0 on 2025-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0022_alter_controlekm_status_alter_despesadiversa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlekm',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado_Regional', 'Aprovado Regional'), ('Aprovado_Matriz', 'Aprovado Matriz'), ('Aprovado_Financeiro', 'Aprovado Financeiro'), ('Pago', 'Pago'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='despesadiversa',
            name='status',
            field=models.CharField(default='Pendente', max_length=50),
        ),
    ]
