# Generated by Django 6.0 on 2026-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0023_alter_controlekm_status_alter_despesadiversa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlekm',
            name='nota_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa'),
        ),
        migrations.AddField(
            model_name='despesadiversa',
            name='nota_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa'),
        ),
    ]
