# Generated by Django 6.0 on 2026-01-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0024_controlekm_nota_recusa_despesadiversa_nota_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlekm',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
