"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from decouple import config, Csv

DEBUG = 'RENDER' not in os.environ


ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


BASE_DIR = Path(__file__).resolve().parent.parent






SECRET_KEY = config('SECRET_KEY')


DEBUG = config('DEBUG', default=true, cast=bool)




RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)




INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core_rh.apps.CoreRhConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'core_rh.middleware.TrocaSenhaObrigatoriaMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sistema_rh',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=True
    )



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True





STATIC_URL = 'static/'


import os

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'),
]






JAZZMIN_SETTINGS = {
    "site_title": "Dividata",
    "site_header": "Dividata",
    "site_brand": "Dividata",
    "site_logo": None,
    "login_logo": None,
    "welcome_sign": "Administração",
    "copyright": "Dividata RH",
    
    "site_url": "/", 

    
   "show_sidebar": False,
    "navigation_expanded": False,

    
    "topmenu_links": [
        
        {"name": "Navegação", "url": "home", "permissions": []}, 
        
        
        {"model": "core_rh.Funcionario"},
        {"model": "core_rh.Equipe"},
        {"model": "core_rh.Cargo"},
    ],

    "hide_apps": ["auth"], 
    "hide_models": ["core_rh.RegistroPonto"], 

    
    "custom_css": "css/admin_theme.css",
    "custom_js": "js/admin_logic.js",
    
    "show_ui_builder": False,
    
    "icons": {
        "core_rh.Funcionario": "fas fa-user-tie",
        "core_rh.Equipe": "fas fa-users",
        "core_rh.Cargo": "fas fa-briefcase",
    },
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-orange", 
    "accent": "accent-orange",       
    "navbar": "navbar-orange navbar-dark", 
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-warning", 
    "theme": "flatly",
    
    
    
    "button_classes": {
        "primary": "btn-primary",     
        "secondary": "btn-secondary", 
        "info": "btn-info",           
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"      
    }
}





LOGIN_URL = 'login' 


LOGIN_REDIRECT_URL = 'home' 


LOGOUT_REDIRECT_URL = 'login'

EMAIL_BACKEND = 'core_rh.email_backend.EmailBackendSemVerificacao' # Seu backend personalizado
EMAIL_HOST = 'mail.dividata360.com.br'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
# AQUI ESTÁ A MUDANÇA:
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'Portal DIVIDATA <devteam@dividata360.com.br>'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core/static')]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core/static')]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CSRF_TRUSTED_ORIGINS = ['https://portalrh.dividata360.com.br']
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None